### ISSUE TITLE
deploy_preview action recently started failing

### ISSUE THREAD

**Issue by mathiasbynens** [v8/v8.dev#485]
Example failure: https://github.com/v8/v8.dev/pull/484/checks?check_run_id=1192564086

```
Error: Input required and not supplied: firebaseServiceAccount
    at Object.i.getInput (/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:3121)
    at Object.<anonymous> (/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:296295)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

AFAICT, we did not make any changes to our config.

cc @jhuleatt, does this sound familiar to you?

**Comment by jhuleatt** [comment]
GitHub doesn't supply secret values to the action when a PR is made from a fork. I've been meaning to document this (https://github.com/FirebaseExtended/action-hosting-deploy/issues/17), sorry it wasn't clear.

![Screen Shot 2020-10-01 at 8 06 17 AM](https://user-images.githubusercontent.com/3759507/94827382-36525600-03bd-11eb-96f1-fbff70b0d10d.png)

There may be a workaround: https://stackoverflow.com/a/58740879/4816918. Would that fit your use case?

**Comment by mathiasbynens** [comment]
Thanks @jhuleatt. Maybe a nice way to "document" this would be to throw an error with an error message that echoes what you said said?
