### ISSUE TITLE
Building embeding V8 instructions produce an error

### ISSUE THREAD

**Issue by achronop** [v8/v8.dev#500]
```
:~/repos/v8/v8$ tools/dev/v8gen.py x64.release.sample

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release.sample', 'out.gn/x64.release.sample']' returned non-zero exit status 1
```

**Comment by achronop** [comment]
```
################################################################################
/usr/bin/python -u tools/mb/mb.py gen -f infra/mb/mb_config.pyl -m developer_default -b x64.release.sample out.gn/x64.release.sample
  
  Writing """\
  android_unstripped_runtime_outputs = false
  is_component_build = false
  is_debug = false
  target_cpu = "x64"
  use_custom_libcxx = false
  v8_monolithic = true
  v8_use_external_startup_data = false
  """ to /home/achronop/repos/v8/v8/out.gn/x64.release.sample/args.gn.
  
  /home/achronop/repos/v8/v8/buildtools/linux64/gn gen out.gn/x64.release.sample --check
    -> returned 1
  ERROR at //BUILD.gn:9:1: Can't load input file.
  import("//build/config/jumbo.gni")
  ^--------------------------------
  Unable to load:
    /home/achronop/repos/v8/v8/build/config/jumbo.gni
  I also checked in the secondary tree for:
    /home/achronop/repos/v8/v8/build/secondary/build/config/jumbo.gni
  GN gen failed: 1
Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release.sample', 'out.gn/x64.release.sample']' returned non-zero exit status 1
```

**Comment by achronop** [comment]
It was my bad, sorry for the inconvenience.
